---
- name: fetch additional dependency
  shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -

- name: install node using yum
  yum:
    name: nodejs
    state: present

- name: install express
  shell: sudo npm install express --save
- name: install body-parser
  shell: sudo npm install body-parser --save
- name: install mongoDB library
  shell: sudo npm install mongodb --save

- name: clone with https
  git:
    repo: https://github.com/TWCurry/CD5108-Coursework.git
    dest: /home/ec2-user/CD5108-Coursework

- name: insert MongoDB ip address
  shell: | 
    cd /home/ec2-user/CD5108-Coursework
    ipaddress=$(aws ec2 describe-instances --filters Name=tag:Name,Values=dbserver --region eu-west-2 | jq -r .Reservations[0].Instances[0].PublicIpAddress)
    sed -i "s/localhost/$ipaddress/" api.js
- name: run nodeJs file
  shell: node /home/ec2-user/CD5108-Coursework/api.js