---
- name: install nodeJs dependencies
  yum: 
    name: -y gcc-c++ make
    state: present 

- name: fetch additional dependency
  shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -

- name: install node using yum
  yum:
    name: nodejs
    state: present

- name: install express
  shell: sudo npm install express --save
- name: install body-parser
  shell: sudo npm install body-parser --save
- name: install mongoDB library
  shell: sudo npm install mongodb --save

- name: clone with https
  git:
    repo: https://github.com/TWCurry/CD5108-Coursework.git
    dest: /home/ec2-user

- name: move api file to home directory
  shell: cd CD5108-Coursework/
  shell: sudo mv api.js /home/ec2-user
  shel: cd ../
- name: run nodeJs file
  shell: node api.js