---
- name: create yum repository
  shell: |
    sudo touch /etc/yum.repos.d/mongodb-org-4.4.repo
    echo "[mongodb-org-4.4]
    name=MongoDB Repository
    baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
    gpgcheck=1
    enabled=1
    gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc" | sudo tee /etc/yum.repos.d/mongodb-org-4.4.repo
- name: install mongoDB
  yum:
    name: mongodb-org
    state: present
- name: run mongodb
  shell: sudo systemctl start mongod
- name: install expect package
  yum:
    name: expect
    state: present
- name: copy expect script
  copy:
    src: ../files/mongo-shell.exp
    dest: /home/ec2-user/mongo-shell.exp
- name: run expect script
  shell: expect mongo-shell.exp
- name: import csv file
  shell: mongoimport --type csv -d CD5108 -c coviddata --headerline --drop Coviddata.csv
- name: open port 27017
  shell: |
    sudo iptables -A INPUT -p tcp --destination-port 27017 -m state --state NEW,ESTABLISHED -j ACCEPT
    sudo iptables -A OUTPUT  -p tcp --source-port 27017 -m state --state ESTABLISHED -j ACCEPT
- name: enable the dbserver to listen on port 27017 for everything
  shell: sudo sed -i "s/127.0.0.1/0.0.0.0/" /etc/mongod.conf